<?php

return array (
  'id' => '4c4d3ebb',
  'created_on' => 1476561189,
  'modified_on' => 0,
  'active' => 1,
  'deleted' => 0,
  'name' => 'General Requirements',
  'description' => 'Generated by migration process',
  'url' => 'index',
  'parent_id' => 'ff178078',
  'target' => 'top',
  'order_seq' => 1,
);