<?php

return
array (
  'id' => 'ff178078',
  'created_on' => 1476561189,
  'modified_on' => 0,
  'active' => 1,
  'deleted' => 0,
  'name' => 'Visa Information',
  'description' => 'Generated by migration process',
  'url' => 'visa',
  'parent_id' => '25683d12',
  'target' => 'top',
  'order_seq' => 2,
);