<?php

return
array (
  'id' => '83294862',
  'created_on' => 1476561181,
  'modified_on' => 0,
  'active' => 1,
  'deleted' => 0,
  'name' => 'Press of Uzbekistan',
  'description' => 'Generated by migration process',
  'url' => 'press-uzbekistan',
  'parent_id' => '0',
  'target' => 'left',
  'order_seq' => 101,
);