<?php

return
array (
  '9ccadd16' =>
  array (
    'id' => '9ccadd16',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'News & Events',
    'description' => 'Generated by migration process',
    'url' => 'news',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 100,
    'children' =>
    array (
    ),
  ),
  83294862 =>
  array (
    'id' => '83294862',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Press of Uzbekistan',
    'description' => 'Generated by migration process',
    'url' => 'press-uzbekistan',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 101,
    'children' =>
    array (
    ),
  ),
  'fd0d745b' =>
  array (
    'id' => 'fd0d745b',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Constitution Day',
    'description' => 'Generated by migration process',
    'url' => 'constitution',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 102,
    'children' =>
    array (
    ),
  ),
  '4d732849' =>
  array (
    'id' => '4d732849',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Uzbek-American Relations',
    'description' => 'Generated by migration process',
    'url' => 'uz_us_relations',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 103,
    'children' =>
    array (
    ),
  ),
  'f1b1a003' =>
  array (
    'id' => 'f1b1a003',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => '25 Years of Independence',
    'description' => 'Generated by migration process',
    'url' => 'independence',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 104,
    'children' =>
    array (
    ),
  ),
  '29aa2a4c' =>
  array (
    'id' => '29aa2a4c',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Presidency of Uzbekistan in SCO',
    'description' => 'Generated by migration process',
    'url' => 'sco2',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 105,
    'children' =>
    array (
    ),
  ),
  '12e6a543' =>
  array (
    'id' => '12e6a543',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Sustainable Development Goals',
    'description' => 'Generated by migration process',
    'url' => 'millennium-development-goals',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 106,
    'children' =>
    array (
    ),
  ),
  '94e8e9cc' =>
  array (
    'id' => '94e8e9cc',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Cooperation within the ILO',
    'description' => 'Generated by migration process',
    'url' => 'cooperation-within-the-ilo',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 107,
    'children' =>
    array (
    ),
  ),
  '3b3bb58c' =>
  array (
    'id' => '3b3bb58c',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Year of Healthy Mother and Child',
    'description' => 'Generated by migration process',
    'url' => 'named-year',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 108,
    'children' =>
    array (
    ),
  ),
  '18bc4194' =>
  array (
    'id' => '18bc4194',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Presidential Elections 2016',
    'description' => 'Generated by migration process',
    'url' => 'presidential-elections',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 109,
    'children' =>
    array (
    ),
  ),
  'b207b2a1' =>
  array (
    'id' => 'b207b2a1',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Celebration of Navruz',
    'description' => 'Generated by migration process',
    'url' => 'navruz',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 110,
    'children' =>
    array (
    ),
  ),
  'be6ceef2' =>
  array (
    'id' => 'be6ceef2',
    'created_on' => 1476561181,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Press Office',
    'description' => 'Generated by migration process',
    'url' => 'press',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 111,
    'children' =>
    array (
    ),
  ),
  '5be25d83' =>
  array (
    'id' => '5be25d83',
    'created_on' => 1476561189,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Social Issues',
    'description' => 'Generated by migration process',
    'url' => 'social_issues',
    'parent_id' => '0',
    'target' => 'left',
    'order_seq' => 200,
    'children' =>
    array (
      '30ebc9ca' =>
      array (
        'id' => '30ebc9ca',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Political Reforms',
        'description' => 'Generated by migration process',
        'url' => 'political_reforms',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 1,
        'children' =>
        array (
        ),
      ),
      'c5835e6c' =>
      array (
        'id' => 'c5835e6c',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Judicial Reforms',
        'description' => 'Generated by migration process',
        'url' => 'judicial_reforms',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 2,
        'children' =>
        array (
        ),
      ),
      'ea9d041f' =>
      array (
        'id' => 'ea9d041f',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Human Rights',
        'description' => 'Generated by migration process',
        'url' => 'human_rights',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 3,
        'children' =>
        array (
        ),
      ),
      'ad9eb89d' =>
      array (
        'id' => 'ad9eb89d',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Children\'s Rights',
        'description' => 'Generated by migration process',
        'url' => 'children_rights',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 4,
        'children' =>
        array (
        ),
      ),
      '11f34a22' =>
      array (
        'id' => '11f34a22',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Religious Freedom',
        'description' => 'Generated by migration process',
        'url' => 'religious_freedom',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 5,
        'children' =>
        array (
        ),
      ),
      'aa94a1e5' =>
      array (
        'id' => 'aa94a1e5',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Human Trafficking',
        'description' => 'Generated by migration process',
        'url' => 'human_trafficking',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 6,
        'children' =>
        array (
        ),
      ),
      '8837bb6f' =>
      array (
        'id' => '8837bb6f',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Prevention of Torture',
        'description' => 'Generated by migration process',
        'url' => 'torture_prevention',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 7,
        'children' =>
        array (
        ),
      ),
      '22b0becd' =>
      array (
        'id' => '22b0becd',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Anti-Corruption Policy',
        'description' => 'Generated by migration process',
        'url' => 'anti_corruption',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 8,
        'children' =>
        array (
        ),
      ),
      '106914ba' =>
      array (
        'id' => '106914ba',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Gender Policy',
        'description' => 'Generated by migration process',
        'url' => 'gender_policy',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 9,
        'children' =>
        array (
        ),
      ),
      'fd4cf46a' =>
      array (
        'id' => 'fd4cf46a',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Support For NGOs',
        'description' => 'Generated by migration process',
        'url' => 'support_for_ngos',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 10,
        'children' =>
        array (
        ),
      ),
      '00f95fb0' =>
      array (
        'id' => '00f95fb0',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Freedom Of Speech',
        'description' => 'Generated by migration process',
        'url' => 'freedom_of_speech',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 11,
        'children' =>
        array (
        ),
      ),
      '9c228e2b' =>
      array (
        'id' => '9c228e2b',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Healthcare Policy',
        'description' => 'Generated by migration process',
        'url' => 'healthcare_policy',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 12,
        'children' =>
        array (
        ),
      ),
      'bd9f4680' =>
      array (
        'id' => 'bd9f4680',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Education Policy',
        'description' => 'Generated by migration process',
        'url' => 'education_policy',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 13,
        'children' =>
        array (
        ),
      ),
      'c7164722' =>
      array (
        'id' => 'c7164722',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Revival of Cultural Values',
        'description' => 'Generated by migration process',
        'url' => 'cultural_values',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 14,
        'children' =>
        array (
        ),
      ),
      'a1da72da' =>
      array (
        'id' => 'a1da72da',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Physical Education and Sports',
        'description' => 'Generated by migration process',
        'url' => 'sports',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 15,
        'children' =>
        array (
        ),
      ),
      'fa9a871f' =>
      array (
        'id' => 'fa9a871f',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Business Climate',
        'description' => 'Generated by migration process',
        'url' => 'business_climate',
        'parent_id' => '5be25d83',
        'target' => 'left',
        'order_seq' => 16,
        'children' =>
        array (
        ),
      ),
    ),
  ),
);