<?php

return
array (
  'e002d712' =>
  array (
    'id' => 'e002d712',
    'created_on' => 1476561189,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Embassy',
    'description' => 'Generated by migration process',
    'url' => 'embassy',
    'parent_id' => '0',
    'target' => 'top',
    'order_seq' => 1,
    'children' =>
    array (
      '6643ba18' =>
      array (
        'id' => '6643ba18',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'About Embassy',
        'description' => 'Generated by migration process',
        'url' => 'about',
        'parent_id' => 'e002d712',
        'target' => 'top',
        'order_seq' => 1,
        'children' =>
        array (
        ),
      ),
      '7626ac67' =>
      array (
        'id' => '7626ac67',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Ambassador',
        'description' => 'Generated by migration process',
        'url' => 'ambassador',
        'parent_id' => 'e002d712',
        'target' => 'top',
        'order_seq' => 2,
        'children' =>
        array (
        ),
      ),
      '566bdfd2' =>
      array (
        'id' => '566bdfd2',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Embassy Holidays',
        'description' => 'Generated by migration process',
        'url' => 'holidays',
        'parent_id' => 'e002d712',
        'target' => 'top',
        'order_seq' => 3,
        'children' =>
        array (
        ),
      ),
      '2c1c5098' =>
      array (
        'id' => '2c1c5098',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Embassy Tour',
        'description' => 'Generated by migration process',
        'url' => 'tour',
        'parent_id' => 'e002d712',
        'target' => 'top',
        'order_seq' => 4,
        'children' =>
        array (
        ),
      ),
    ),
  ),
  '25683d12' =>
  array (
    'id' => '25683d12',
    'created_on' => 1476561189,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Consular Section',
    'description' => 'Generated by migration process',
    'url' => 'consular',
    'parent_id' => '0',
    'target' => 'top',
    'order_seq' => 2,
    'children' =>
    array (
      '124e0636' =>
      array (
        'id' => '124e0636',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'General Information',
        'description' => 'Generated by migration process',
        'url' => 'main',
        'parent_id' => '25683d12',
        'target' => 'top',
        'order_seq' => 1,
        'children' =>
        array (
        ),
      ),
      'ff178078' =>
      array (
        'id' => 'ff178078',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Visa Information',
        'description' => 'Generated by migration process',
        'url' => 'visa',
        'parent_id' => '25683d12',
        'target' => 'top',
        'order_seq' => 2,
        'children' =>
        array (
          '4c4d3ebb' =>
          array (
            'id' => '4c4d3ebb',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'General Requirements',
            'description' => 'Generated by migration process',
            'url' => 'index',
            'parent_id' => 'ff178078',
            'target' => 'top',
            'order_seq' => 1,
            'children' =>
            array (
            ),
          ),
          '9a82a962' =>
          array (
            'id' => '9a82a962',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Requirements for US Citizens',
            'description' => 'Generated by migration process',
            'url' => 'us_citizens_requirements',
            'parent_id' => 'ff178078',
            'target' => 'top',
            'order_seq' => 2,
            'children' =>
            array (
            ),
          ),
          '3f8c82ad' =>
          array (
            'id' => '3f8c82ad',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Visa Fees',
            'description' => 'Generated by migration process',
            'url' => 'fee',
            'parent_id' => 'ff178078',
            'target' => 'top',
            'order_seq' => 3,
            'children' =>
            array (
            ),
          ),
        ),
      ),
      '0a61db58' =>
      array (
        'id' => '0a61db58',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Consular Services',
        'description' => 'Generated by migration process',
        'url' => 'services',
        'parent_id' => '25683d12',
        'target' => 'top',
        'order_seq' => 3,
        'children' =>
        array (
          '4447bf09' =>
          array (
            'id' => '4447bf09',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Biometric Passport',
            'description' => 'Generated by migration process',
            'url' => 'biometric_passport',
            'parent_id' => '0a61db58',
            'target' => 'top',
            'order_seq' => 1,
            'children' =>
            array (
            ),
          ),
          '7f53de5f' =>
          array (
            'id' => '7f53de5f',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Obtaining Documents',
            'description' => 'Generated by migration process',
            'url' => 'obtaining_documents',
            'parent_id' => '0a61db58',
            'target' => 'top',
            'order_seq' => 2,
            'children' =>
            array (
            ),
          ),
        ),
      ),
      'de3861f5' =>
      array (
        'id' => 'de3861f5',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Legal Services',
        'description' => 'Generated by migration process',
        'url' => 'legal',
        'parent_id' => '25683d12',
        'target' => 'top',
        'order_seq' => 4,
        'children' =>
        array (
          '8424f145' =>
          array (
            'id' => '8424f145',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Apostille',
            'description' => 'Generated by migration process',
            'url' => 'apostil',
            'parent_id' => 'de3861f5',
            'target' => 'top',
            'order_seq' => 1,
            'children' =>
            array (
            ),
          ),
          'ba76edab' =>
          array (
            'id' => 'ba76edab',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Power-of-Attorney',
            'description' => 'Generated by migration process',
            'url' => 'power_of_attorney',
            'parent_id' => 'de3861f5',
            'target' => 'top',
            'order_seq' => 2,
            'children' =>
            array (
            ),
          ),
        ),
      ),
      '744ceb01' =>
      array (
        'id' => '744ceb01',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Useful Information',
        'description' => 'Generated by migration process',
        'url' => 'useful',
        'parent_id' => '25683d12',
        'target' => 'top',
        'order_seq' => 5,
        'children' =>
        array (
          'bb58305a' =>
          array (
            'id' => 'bb58305a',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Phone Dialing Codes',
            'description' => 'Generated by migration process',
            'url' => 'phonecodes',
            'parent_id' => '744ceb01',
            'target' => 'top',
            'order_seq' => 1,
            'children' =>
            array (
            ),
          ),
          '80e2915b' =>
          array (
            'id' => '80e2915b',
            'created_on' => 1476561189,
            'modified_on' => 0,
            'active' => 1,
            'deleted' => 0,
            'name' => 'Travel Agencies',
            'description' => 'Generated by migration process',
            'url' => 'travelagencies',
            'parent_id' => '744ceb01',
            'target' => 'top',
            'order_seq' => 2,
            'children' =>
            array (
            ),
          ),
        ),
      ),
      '8a60b3fe' =>
      array (
        'id' => '8a60b3fe',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Contact Us',
        'description' => 'Generated by migration process',
        'url' => 'contact',
        'parent_id' => '25683d12',
        'target' => 'top',
        'order_seq' => 6,
        'children' =>
        array (
        ),
      ),
    ),
  ),
  '82e0c8f6' =>
  array (
    'id' => '82e0c8f6',
    'created_on' => 1476561189,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Economy and Trade',
    'description' => 'Generated by migration process',
    'url' => 'economy_and_trade',
    'parent_id' => '0',
    'target' => 'top',
    'order_seq' => 3,
    'children' =>
    array (
      'c96f3bcb' =>
      array (
        'id' => 'c96f3bcb',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Progress in 2014',
        'description' => 'Generated by migration process',
        'url' => 'progress',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 1,
        'children' =>
        array (
        ),
      ),
      '3f4b785e' =>
      array (
        'id' => '3f4b785e',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Investment Climate',
        'description' => 'Generated by migration process',
        'url' => 'climate',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 2,
        'children' =>
        array (
        ),
      ),
      '7759a480' =>
      array (
        'id' => '7759a480',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Oil and Gas',
        'description' => 'Generated by migration process',
        'url' => 'oilandgas',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 3,
        'children' =>
        array (
        ),
      ),
      '8d1f0c0d' =>
      array (
        'id' => '8d1f0c0d',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Energy Sector',
        'description' => 'Generated by migration process',
        'url' => 'energy',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 4,
        'children' =>
        array (
        ),
      ),
      '583694b8' =>
      array (
        'id' => '583694b8',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Transportation Network',
        'description' => 'Generated by migration process',
        'url' => 'transportation',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 5,
        'children' =>
        array (
        ),
      ),
      'eccfb855' =>
      array (
        'id' => 'eccfb855',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Electrical Engineering',
        'description' => 'Generated by migration process',
        'url' => 'ee',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 6,
        'children' =>
        array (
        ),
      ),
      'a11da725' =>
      array (
        'id' => 'a11da725',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Chemical Industry',
        'description' => 'Generated by migration process',
        'url' => 'chemical',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 7,
        'children' =>
        array (
        ),
      ),
      '42645b00' =>
      array (
        'id' => '42645b00',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Investment Projects',
        'description' => 'Generated by migration process',
        'url' => 'projects',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 8,
        'children' =>
        array (
        ),
      ),
      'b802b741' =>
      array (
        'id' => 'b802b741',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Project for Technical Assistance',
        'description' => 'Generated by migration process',
        'url' => 'project-for-technical-assistance',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 9,
        'children' =>
        array (
        ),
      ),
      '7d986558' =>
      array (
        'id' => '7d986558',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Privatization Projects',
        'description' => 'Generated by migration process',
        'url' => 'http://uzbekistan.org/files/economy/privatization-projects-final-list.doc',
        'parent_id' => '82e0c8f6',
        'target' => 'top',
        'order_seq' => 10,
        'children' =>
        array (
        ),
      ),
    ),
  ),
  '94c4f9fb' =>
  array (
    'id' => '94c4f9fb',
    'created_on' => 1476561189,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Media Gallery',
    'description' => 'Generated by migration process',
    'url' => 'gallery',
    'parent_id' => '0',
    'target' => 'top',
    'order_seq' => 9,
    'children' =>
    array (
      'e38d3a4b' =>
      array (
        'id' => 'e38d3a4b',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Photo Gallery',
        'description' => 'Generated by migration process',
        'url' => 'photo',
        'parent_id' => '94c4f9fb',
        'target' => 'top',
        'order_seq' => 1,
        'children' =>
        array (
        ),
      ),
      '49daf26c' =>
      array (
        'id' => '49daf26c',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Video Gallery',
        'description' => 'Generated by migration process',
        'url' => 'video',
        'parent_id' => '94c4f9fb',
        'target' => 'top',
        'order_seq' => 2,
        'children' =>
        array (
        ),
      ),
      'a9a6f229' =>
      array (
        'id' => 'a9a6f229',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Tourism',
        'description' => 'Generated by migration process',
        'url' => 'tourism',
        'parent_id' => '94c4f9fb',
        'target' => 'top',
        'order_seq' => 3,
        'children' =>
        array (
        ),
      ),
    ),
  ),
  'd1a30c6b' =>
  array (
    'id' => 'd1a30c6b',
    'created_on' => 1476561189,
    'modified_on' => 0,
    'active' => 1,
    'deleted' => 0,
    'name' => 'Uzbekistan',
    'description' => 'Generated by migration process',
    'url' => 'uzbekistan',
    'parent_id' => '0',
    'target' => 'top',
    'order_seq' => 10,
    'children' =>
    array (
      '31b85fdb' =>
      array (
        'id' => '31b85fdb',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'About Uzbekistan',
        'description' => 'Generated by migration process',
        'url' => 'about',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 1,
        'children' =>
        array (
        ),
      ),
      '5bbef4b4' =>
      array (
        'id' => '5bbef4b4',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Geography',
        'description' => 'Generated by migration process',
        'url' => 'geography',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 2,
        'children' =>
        array (
        ),
      ),
      '4c375719' =>
      array (
        'id' => '4c375719',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'State Symbols',
        'description' => 'Generated by migration process',
        'url' => 'symbols',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 3,
        'children' =>
        array (
        ),
      ),
      'ce8044be' =>
      array (
        'id' => 'ce8044be',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Political Structure',
        'description' => 'Generated by migration process',
        'url' => 'political',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 4,
        'children' =>
        array (
        ),
      ),
      'bd22b46d' =>
      array (
        'id' => 'bd22b46d',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Population',
        'description' => 'Generated by migration process',
        'url' => 'people',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 5,
        'children' =>
        array (
        ),
      ),
      '4e213aba' =>
      array (
        'id' => '4e213aba',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'History',
        'description' => 'Generated by migration process',
        'url' => 'history',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 6,
        'children' =>
        array (
        ),
      ),
      '8c3fcc64' =>
      array (
        'id' => '8c3fcc64',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Travel Info',
        'description' => 'Generated by migration process',
        'url' => 'travel',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 7,
        'children' =>
        array (
        ),
      ),
      '5e694ace' =>
      array (
        'id' => '5e694ace',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Culture and Traditions',
        'description' => 'Generated by migration process',
        'url' => 'culture',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 8,
        'children' =>
        array (
        ),
      ),
      '166c2787' =>
      array (
        'id' => '166c2787',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'National Holidays',
        'description' => 'Generated by migration process',
        'url' => 'national_holidays',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 9,
        'children' =>
        array (
        ),
      ),
      '38aeaa78' =>
      array (
        'id' => '38aeaa78',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Health',
        'description' => 'Generated by migration process',
        'url' => 'Health',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 10,
        'children' =>
        array (
        ),
      ),
      '57c71be2' =>
      array (
        'id' => '57c71be2',
        'created_on' => 1476561189,
        'modified_on' => 0,
        'active' => 1,
        'deleted' => 0,
        'name' => 'Science and Education',
        'description' => 'Generated by migration process',
        'url' => 'science_and_education',
        'parent_id' => 'd1a30c6b',
        'target' => 'top',
        'order_seq' => 11,
        'children' =>
        array (
        ),
      ),
    ),
  ),
);